import { useState } from 'react'
import Papa from 'papaparse'
import { PLAN_LIMITS, type PlanType } from '@/lib/limits'
import { sanitizeString } from '@/lib/security/validation-schemas'
import { env } from '@/config/env'
import { parseXls } from '@/lib/xls-parser'
import { SpreadsheetParseError, type ParseErrorCode } from '@/lib/spreadsheet-errors'

export interface ParseResult {
  columns: string[]
  rowCount: number
  preview?: Record<string, string | number | boolean | null>[]
}

export interface ParseError {
  message: string
  code: ParseErrorCode
}

/** Build the params consumed by the `errors.parseRowLimit` i18n message. */
/**
 * Params for the `errors.parseRowLimit` message. `plan` carries the plan TYPE
 * (e.g. "free") — the localized name is resolved later by toast-error via t().
 */
function rowLimitParams(total: number, max: number, plan: PlanType): Record<string, string> {
  return { total: String(total), max: String(max), plan }
}

type PreviewRow = Record<string, string | number | boolean | null>

/** Sanitize all string values in preview rows to prevent XSS */
function sanitizePreviewRows(rows: PreviewRow[]): PreviewRow[] {
  return rows.map((row) => {
    const sanitized: PreviewRow = {}
    for (const [key, value] of Object.entries(row)) {
      sanitized[key] = typeof value === 'string' ? sanitizeString(value) : value
    }
    return sanitized
  })
}

const MAX_CLIENT_PARSE_SIZE = 10 * 1024 * 1024 // 10MB

/**
 * Hook for parsing spreadsheet files (XLSX, CSV) in the browser
 * Automatically falls back to server-side parsing for files > 10MB
 */
export function useFileParser() {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<ParseError | null>(null)

  /**
   * Parse file in browser (client-side).
   * CSV via PapaParse; .xls/.xlsx/.xlsm via SheetJS in an isolated Web Worker.
   * Enforces row limits based on plan and sanitizes column names.
   */
  const parseFileInBrowser = async (file: File, plan: PlanType = 'free'): Promise<ParseResult> => {
    const limits = PLAN_LIMITS[plan]
    const buffer = await file.arrayBuffer()

    // CSV files
    if (file.name.toLowerCase().endsWith('.csv')) {
      const text = new TextDecoder().decode(buffer)

      // First pass: count total rows to validate against limit
      const fullParse = Papa.parse(text, {
        header: true,
        skipEmptyLines: true,
      })

      if (fullParse.errors.length > 0) {
        throw new SpreadsheetParseError('CORRUPT_FILE', fullParse.errors[0].message)
      }

      const totalRows = fullParse.data.length
      if (totalRows > limits.maxRows) {
        throw new SpreadsheetParseError(
          'ROW_LIMIT',
          `File exceeds row limit: ${totalRows} rows (max ${limits.maxRows} for ${limits.name} plan)`,
          rowLimitParams(totalRows, limits.maxRows, plan),
        )
      }

      // Sanitize column names to prevent XSS
      const rawColumns = fullParse.meta.fields || []
      const columns = rawColumns.map((col) => sanitizeString(col)).filter((col) => col.length > 0)

      if (columns.length === 0) {
        throw new SpreadsheetParseError('NO_COLUMNS', 'No columns found in first row')
      }

      return {
        columns,
        rowCount: totalRows,
        preview: sanitizePreviewRows((fullParse.data as PreviewRow[]).slice(0, 5)),
      }
    }

    const name = file.name.toLowerCase()

    // Excel (.xls legacy + .xlsx/.xlsm modern) — SheetJS in an isolated Web Worker.
    // SheetJS is far more tolerant than ExcelJS, which throws on valid files whose
    // internal [Content_Types].xml differs from Excel's own output (e.g. files
    // generated by pandas/openpyxl/LibreOffice declare the workbook via a Default
    // for "xml" instead of an Override — ExcelJS then fails with "reading 'sheets'").
    // Running SheetJS in the Worker also isolates CVE-2023-30533.
    if (name.endsWith('.xls') || name.endsWith('.xlsx') || name.endsWith('.xlsm')) {
      const result = await parseXls(buffer)

      const columns = result.columns
        .map((col) => sanitizeString(col))
        .filter((col) => col.length > 0)

      if (columns.length === 0) {
        throw new SpreadsheetParseError('NO_COLUMNS', 'No columns found in first row')
      }

      if (result.rowCount > limits.maxRows) {
        throw new SpreadsheetParseError(
          'ROW_LIMIT',
          `File exceeds row limit: ${result.rowCount} rows (max ${limits.maxRows} for ${limits.name} plan)`,
          rowLimitParams(result.rowCount, limits.maxRows, plan),
        )
      }

      const preview = sanitizePreviewRows(result.rows.slice(0, 5) as PreviewRow[])

      return {
        columns,
        rowCount: result.rowCount,
        preview,
      }
    }

    throw new SpreadsheetParseError('UNSUPPORTED_FORMAT', 'Unsupported file format')
  }

  /**
   * Parse file on server (fallback for large files)
   */
  const parseFileInServer = async (file: File): Promise<ParseResult> => {
    const formData = new FormData()
    formData.append('files', file)

    const response = await fetch('/api/preview', {
      method: 'POST',
      body: formData,
    })

    if (!response.ok) {
      const data = await response.json()
      throw new Error(data.error || 'Failed to parse file on server')
    }

    const data = await response.json()
    return {
      columns: data.columns || [],
      rowCount: data.rowCount || 0,
    }
  }

  /**
   * Smart parsing: client-side for small files, server-side for large files
   */
  const parseFile = async (file: File, plan: PlanType = 'free'): Promise<ParseResult> => {
    setIsLoading(true)
    setError(null)

    try {
      let result: ParseResult

      if (file.size < MAX_CLIENT_PARSE_SIZE) {
        // Small file: parse in browser (instant, no server load)
        result = await parseFileInBrowser(file, plan)
      } else {
        // Large file: parse on server (avoid browser freeze)
        result = await parseFileInServer(file)
      }

      setIsLoading(false)
      return result
    } catch (err) {
      if (env.NODE_ENV !== 'production') {
        console.error('[useFileParser]', err)
      }

      // Preserve the precise error code so the UI shows what actually happened.
      // Anything that isn't already a SpreadsheetParseError is genuinely
      // unexpected — wrap it as UNKNOWN (mapped to a safe, non-leaking message).
      const parseError =
        err instanceof SpreadsheetParseError
          ? err
          : new SpreadsheetParseError(
              'UNKNOWN',
              err instanceof Error ? err.message : 'Unknown parsing error',
            )

      setError({ message: parseError.message, code: parseError.code })
      setIsLoading(false)
      throw parseError
    }
  }

  return {
    parseFile,
    isLoading,
    error,
  }
}
